### ISSUE TITLE
Broken Links in Fixing Nav Mesh Build Issues

### ISSUE THREAD

**Issue by CarsonBarry** [The-Scripters-Guild/ForgeWiki#13]
article
https://wiki.thescriptersguild.com/main/halo-infinite/guides-and-tutorials/forge/nav-mesh/fixing-nav-mesh-build-issues

broken links
https://github.com/The-Scripters-Guild/ForgeWiki/blob/main/main/halo-infinite/forge/nav-mesh/nav-mesh-generation-root-points/README.md
https://github.com/The-Scripters-Guild/ForgeWiki/blob/main/main/halo-infinite/forge/player-spawning/backup-spawn-points/README.md
https://github.com/The-Scripters-Guild/ForgeWiki/blob/main/main/halo-infinite/forge/folder-structure/README.md
https://github.com/The-Scripters-Guild/ForgeWiki/blob/main/main/halo-infinite/guides-and-tutorials/forge/forge-mode-in-custom-games/README.md
https://github.com/The-Scripters-Guild/ForgeWiki/blob/main/main/halo-infinite/guides-and-tutorials/forge/forge-mode-in-custom-games/README.md

Pages were not all in best location, had non-capitalized titles.

Fix is to add content for pages and update links to titles.

**Comment by Okom1** [comment]
Please give suggestions for better locations for the articles

**Comment by Okom1** [comment]
Added article for https://github.com/The-Scripters-Guild/ForgeWiki/blob/main/halo-infinite/forge/nav-mesh/nav-mesh-generation-root-points.md in pull request https://github.com/The-Scripters-Guild/ForgeWiki/pull/17

Added article for https://github.com/The-Scripters-Guild/ForgeWiki/blob/main/halo-infinite/forge/player-spawning/backup-spawn-points.md in pull request https://github.com/The-Scripters-Guild/ForgeWiki/pull/19

**Comment by Okom1** [comment]
Fixed up bad link redirects with PR https://github.com/The-Scripters-Guild/ForgeWiki/pull/21

Articles for "Folder Structure" and "Forge via Custom Game" are still not written.

**Comment by Okom1** [comment]
All fixed in https://github.com/The-Scripters-Guild/ForgeWiki/pull/40

Articles for "Folder Structure" and "Forge via Custom Game" are still not written.
