### ISSUE TITLE
Create pages and import content for Blender2Forge tool

### ISSUE THREAD

**Issue by CarsonBarry** [The-Scripters-Guild/ForgeWiki#5]
B2FP pages need added and the documentation for that project needs formatted and imported into the wiki.

**Comment by TubbyMcFatDuck** [comment]
At this time, I am no longer managing my project... Its been passed on to "Larry and Curly"... Depending on how detailed you want the documentation; I can tell you why I picked certain Python dependencies and how the code functions at all levels. If you just want surface level how this works, I can write that out also.

**Comment by CarsonBarry** [comment]
I've got the basics pulled in. Anyone from that team is now able to update those pages or add more to that section via pull requests for the repo. 

It's not important who is managing it, just that the information is accurate and helpful.
